public class SalesforceDeveloper {
    public void myFirstCode(){
        system.debug('Antalya');
        system.debug('Goodfellas');
        system.debug('Summer');
    }

    public void myFavorites(){
        string myFavCity = 'Istanbul';
        Integer myFavNum = 7;
        system.debug(myFavNum);
        system.debug(myFavCity);
        system.debug('My favorite City is -->' + myFavCity + ' and My favorite Number is -->'+ myFavNum);

    }
}