/* DML_Assign1.insertRecords();
Write the SOQL query for the following requirements:
1. Fetch Account Id, Contact First Name, Contact Last Name and Email Address for all the contacts
present in your org.
2. Fetch all the accounts which have no Phone number populated and order them based on the
Account Name in the ascending order.
3. Find all contacts which have no account attached to them.
4. Find out the count of all opportunities present in the Org. */